
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { toast } from "@/hooks/use-toast";
import { Plus } from "lucide-react";
import { createArticle, type BlogArticleInsert } from "@/lib/blogService";
import { ArticleBasicFields } from "./article/ArticleBasicFields";
import { ArticleMetaFields } from "./article/ArticleMetaFields";
import { ArticleSettings } from "./article/ArticleSettings";

interface CreateArticleDialogProps {
  onArticleCreated: () => void;
}

export const CreateArticleDialog = ({ onArticleCreated }: CreateArticleDialogProps) => {
  const [open, setOpen] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [formData, setFormData] = useState({
    title: '',
    content: '',
    excerpt: '',
    meta_description: '',
    meta_keywords: '',
    featured_image: '',
    author_name: '',
    author_role: '',
    category: '',
    tags: '',
    featured: false,
    status: 'draft' as 'draft' | 'published'
  });

  const handleFormDataChange = (field: string, value: string | boolean) => {
    setFormData(prev => ({ ...prev, [field]: value }));
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsSubmitting(true);

    try {
      const articleData: BlogArticleInsert = {
        title: formData.title,
        slug: '', // This will be generated by the createArticle function
        content: formData.content,
        excerpt: formData.excerpt || undefined,
        meta_description: formData.meta_description || undefined,
        meta_keywords: formData.meta_keywords ? formData.meta_keywords.split(',').map(k => k.trim()) : undefined,
        featured_image: formData.featured_image || undefined,
        author_name: formData.author_name,
        author_role: formData.author_role || undefined,
        category: formData.category || undefined,
        tags: formData.tags ? formData.tags.split(',').map(t => t.trim()) : undefined,
        featured: formData.featured,
        status: formData.status,
        published_date: formData.status === 'published' ? new Date().toISOString() : undefined
      };

      await createArticle(articleData);
      
      toast({
        title: "Article Created",
        description: `Article "${formData.title}" has been created successfully.`,
      });

      // Reset form
      setFormData({
        title: '',
        content: '',
        excerpt: '',
        meta_description: '',
        meta_keywords: '',
        featured_image: '',
        author_name: '',
        author_role: '',
        category: '',
        tags: '',
        featured: false,
        status: 'draft'
      });

      setOpen(false);
      onArticleCreated();
    } catch (error) {
      console.error('Failed to create article:', error);
      toast({
        title: "Error",
        description: "Failed to create article. Please try again.",
        variant: "destructive",
      });
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        <Button className="bg-purple-600 hover:bg-purple-700">
          <Plus className="h-4 w-4 mr-2" />
          Create Article
        </Button>
      </DialogTrigger>
      <DialogContent className="max-w-5xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>Create New Blog Article</DialogTitle>
          <DialogDescription>
            Create an SEO-optimized blog article with rich text formatting support.
          </DialogDescription>
        </DialogHeader>
        
        <form onSubmit={handleSubmit} className="space-y-6">
          <ArticleBasicFields formData={formData} onFormDataChange={handleFormDataChange} />
          
          <ArticleMetaFields formData={formData} onFormDataChange={handleFormDataChange} />

          <ArticleSettings formData={formData} onFormDataChange={handleFormDataChange} />

          <div className="flex justify-end gap-4">
            <Button type="button" variant="outline" onClick={() => setOpen(false)}>
              Cancel
            </Button>
            <Button type="submit" disabled={isSubmitting}>
              {isSubmitting ? 'Creating...' : 'Create Article'}
            </Button>
          </div>
        </form>
      </DialogContent>
    </Dialog>
  );
};
