// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xuhrvfslcojpkwwmjioc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh1aHJ2ZnNsY29qcGt3d21qaW9jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NDgzMTUsImV4cCI6MjA2NTUyNDMxNX0.kBAiefXsWmcXFKBYLl27qYDT1WepI2xZMHWkvrmdY4c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);